<?php


/**
 * @file
 * Primary module hooks and main functions for Budweiser Api Football module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
define('SECONDS_DAY', 86400);

/**
 * Implements hook_cron().
 */
function budweiser_api_football_cron() {
  //  Loading teams
  $teams_runtime = \Drupal::state()->get('teams_api_runtime') ?? 0;
  if($teams_runtime+SECONDS_DAY < time()){
    \Drupal::state()->set('teams_api_runtime', time());
    $teams_premier_api = _budweiser_api_football_get_teams(PREMIER_LEAGUE);
    $teams_santander_api = _budweiser_api_football_get_teams(LIGA_SANTANDER);
    if($teams_premier_api && $teams_santander_api){
      $queue = \Drupal::queue('budweiser_api_teams_queue');
      $queue->createQueue();
      $teams_premier = json_decode($teams_premier_api, TRUE);
      $teams_santander = json_decode($teams_santander_api, TRUE);
      foreach($teams_premier['api']['teams'] as $team){
        $queue->createItem($team);
      }
      foreach($teams_santander['api']['teams'] as $team){
        $queue->createItem($team);
      }
    }
  }
}
/**
 * Get Player object by id
 * @param int $player_id
 */
function _budweiser_api_football_get_player_statistics($player_id = 0){
  $curl = curl_init();
  $url = \Drupal::config('budweiser_api_football.settings')->get('api_url')."/players/player/{$player_id}";
  $host = \Drupal::config('budweiser_api_football.settings')->get('api_host');
  $key = \Drupal::config('budweiser_api_football.settings')->get('api_key');
  if($url && $host && $key){
    curl_setopt_array($curl, array(
      CURLOPT_URL => $url,
      CURLOPT_RETURNTRANSFER => true,
      CURLOPT_FOLLOWLOCATION => true,
      CURLOPT_ENCODING => "",
      CURLOPT_MAXREDIRS => 10,
      CURLOPT_TIMEOUT => 30,
      CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
      CURLOPT_CUSTOMREQUEST => "GET",
      CURLOPT_HTTPHEADER => array(
        "x-rapidapi-host: $host",
        "x-rapidapi-key: $key"
      ),
    ));

    $response = curl_exec($curl);
    $err = curl_error($curl);

    curl_close($curl);

    if ($err) {
      \Drupal::logger('')->notice("Curl Error Player = {$err}");
    } else {
      return $response;
    }
  }else{
    \Drupal::messenger()->addMessage('Por favor diligencie los datos de configuración del API');
    return false;
  }
}

/**
 * Get all teams by league id.
 * @param int $league_id
 */
function _budweiser_api_football_get_teams($league_id = 0){
  $curl = curl_init();
  $url = \Drupal::config('budweiser_api_football.settings')->get('api_url')."/teams/league/{$league_id}";
  $host = \Drupal::config('budweiser_api_football.settings')->get('api_host');
  $key = \Drupal::config('budweiser_api_football.settings')->get('api_key');
  if($url && $host && $key) {
    curl_setopt_array($curl, [
      CURLOPT_URL => $url,
      CURLOPT_RETURNTRANSFER => TRUE,
      CURLOPT_FOLLOWLOCATION => TRUE,
      CURLOPT_ENCODING => "",
      CURLOPT_MAXREDIRS => 10,
      CURLOPT_TIMEOUT => 30,
      CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
      CURLOPT_CUSTOMREQUEST => "GET",
      CURLOPT_HTTPHEADER => [
        "x-rapidapi-host: $host",
        "x-rapidapi-key: $key"
      ],
    ]);

    $response = curl_exec($curl);
    $err = curl_error($curl);

    curl_close($curl);

    if ($err) {
      \Drupal::logger('')->notice("Curl Error Player = {$err}");
    }
    else {
      return $response;
    }
  }else{
    \Drupal::messenger()->addMessage('Por favor diligencie los datos de configuración del API');
    return false;
  }
}
